interface AiMetadata {
  generator: string;
  model: string;
  timestamp: string;
}

interface ThreatReport {
  executive_summary: string;
  verdict: string;
  verdict_rationale: string;
  key_findings: string[];
  recommendations: string[];
}

interface ResultsAnalysis {
  enabled: boolean;
  error?: string;
  per_check?: Array<{
    name: string;
    status: string;
    summary_sentence: string;
    risk_level: string;
  }>;
  threat_report?: ThreatReport;
  metadata?: AiMetadata;
}

interface ContentAnalysis {
  enabled: boolean;
  error?: string;
  grammar_issues?: string;
  too_good_claims?: string;
  credential_or_payment_risk?: string;
  brand_mismatch?: string;
  generic_content?: string;
  phishy_tone?: string;
  overall_risk?: string;
  summary?: string;
}

function getAiConfig() {
  return {
    provider: (process.env.AI_PROVIDER || 'nim').toLowerCase(),
    apiKey: process.env.NVIDIA_NIM_API_KEY || '',
    baseUrl: (process.env.NVIDIA_NIM_BASE_URL || 'https://integrate.api.nvidia.com/v1').replace(/\/$/, ''),
    model: process.env.NVIDIA_NIM_MODEL || 'meta/llama-3.1-70b-instruct',
    timeoutMs: Number(process.env.NVIDIA_NIM_TIMEOUT || 90) * 1000,
  };
}

function truncate(value: string, limit: number): string {
  return value.length <= limit ? value : `${value.slice(0, limit - 3)}...`;
}

function extractJson(text: string): Record<string, unknown> {
  let raw = text.trim();
  if (raw.includes('```json')) raw = raw.split('```json', 2)[1].split('```', 1)[0].trim();
  else if (raw.includes('```')) raw = raw.split('```', 2)[1].split('```', 1)[0].trim();
  return JSON.parse(raw) as Record<string, unknown>;
}

function statusToRisk(status: string): string {
  const normalized = (status || '').toUpperCase();
  if (normalized === 'FAIL') return 'HIGH';
  if (normalized === 'WARN') return 'MODERATE';
  return 'LOW';
}

function normalizeVerdict(value: unknown): string {
  const text = String(value || '').trim().toUpperCase();
  if (['BENIGN', 'SUSPICIOUS', 'MALICIOUS'].includes(text)) return text;
  if (['LOW', 'SAFE', 'MINIMAL'].includes(text)) return 'BENIGN';
  if (['MEDIUM', 'MODERATE'].includes(text)) return 'SUSPICIOUS';
  if (['HIGH', 'CRITICAL', 'SEVERE', 'DANGEROUS'].includes(text)) return 'MALICIOUS';
  return 'UNKNOWN';
}

function normalizeList(value: unknown): string[] {
  if (Array.isArray(value)) return value.map((item) => String(item).trim()).filter(Boolean);
  if (typeof value === 'string') return value.split('\n').map((line) => line.trim().replace(/^[-•]\s*/, '')).filter(Boolean);
  return [];
}

function normalizeThreatReport(report: unknown): ThreatReport {
  const source = report && typeof report === 'object' ? report as Record<string, unknown> : {};
  return {
    executive_summary: String(source.executive_summary || source.summary || 'The scan found mixed signals. Review failed and warning checks first.').trim(),
    verdict: normalizeVerdict(source.verdict || source.risk_level),
    verdict_rationale: String(source.verdict_rationale || source.rationale || source.analysis || 'Verdict is based on the number and severity of failed and warning checks.').trim(),
    key_findings: normalizeList(source.key_findings).length ? normalizeList(source.key_findings) : ['No detailed findings were generated by the model.'],
    recommendations: normalizeList(source.recommendations).length ? normalizeList(source.recommendations) : ['Review high-risk checks and remediate the flagged issues.'],
  };
}

function normalizeMetadata(metadata: unknown, model: string): AiMetadata {
  const source = metadata && typeof metadata === 'object' ? metadata as Record<string, unknown> : {};
  return {
    generator: String(source.generator || 'nvidia_nim'),
    model: String(source.model || model),
    timestamp: String(source.timestamp || new Date().toISOString()),
  };
}

async function postChatCompletion(prompt: string, maxTokens: number): Promise<Record<string, unknown>> {
  const config = getAiConfig();
  if (config.provider !== 'nim') return { enabled: false, error: `Unsupported AI provider: ${config.provider}` };
  if (!config.apiKey) return { enabled: false, error: 'NVIDIA_NIM_API_KEY not configured' };

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), Math.max(1000, config.timeoutMs));
  try {
    const response = await fetch(`${config.baseUrl}/chat/completions`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: config.model,
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.2,
        max_tokens: maxTokens,
      }),
      signal: controller.signal,
    });
    if (!response.ok) {
      return { enabled: false, error: `NIM API error: ${response.status}` };
    }

    const json = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
    const content = json.choices?.[0]?.message?.content || '';
    return { enabled: true, payload: extractJson(content) };
  } catch (error) {
    return { enabled: false, error: error instanceof Error ? error.message : String(error) };
  } finally {
    clearTimeout(timer);
  }
}

export async function analyzeTextWithNim(pageText: string, domain: string): Promise<ContentAnalysis> {
  const prompt = `Analyze this webpage for phishing/security risks. Domain: ${domain}

Text: ${pageText.slice(0, 8000)}

Respond with JSON only:
{
  "grammar_issues": "YES|NO: reason",
  "too_good_claims": "YES|NO: reason",
  "credential_or_payment_risk": "YES|NO: reason",
  "brand_mismatch": "YES|NO: reason",
  "generic_content": "YES|NO: reason",
  "phishy_tone": "YES|NO: reason",
  "overall_risk": "LOW|MEDIUM|HIGH",
  "summary": "one sentence"
}`;

  const result = await postChatCompletion(prompt, 1200);
  if (!result.enabled) return result as ContentAnalysis;
  return { enabled: true, ...(result.payload as Record<string, string>) };
}

export async function analyzeResultsWithNim(results: Array<{ id: number; name: string; status: string; evidence: string; data?: Record<string, unknown> }>): Promise<ResultsAnalysis> {
  const config = getAiConfig();
  const payload = {
    counts: results.reduce<Record<string, number>>((acc, result) => {
      const status = (result.status || 'INFO').toUpperCase();
      acc[status] = (acc[status] || 0) + 1;
      return acc;
    }, { PASS: 0, WARN: 0, FAIL: 0, INFO: 0, SKIP: 0 }),
    checks: results.map((result) => ({
      id: result.id,
      name: result.name,
      status: (result.status || 'INFO').toUpperCase(),
      evidence: truncate(result.evidence || '', 240),
      data_excerpt: truncate(JSON.stringify(result.data || {}), 700),
    })),
  };

  const prompt = `Analyze these URL security check results and create a threat report.
Use plain English so a non-technical user can understand it.
Keep wording short and clear. Avoid jargon whenever possible.

Checks payload: ${JSON.stringify(payload)}

Respond with JSON only:
{
  "per_check": [
    {"name": "check name", "status": "PASS|WARN|FAIL|INFO|SKIP", "summary_sentence": "simple one-line explanation", "risk_level": "LOW|MODERATE|HIGH"}
  ],
  "threat_report": {
    "executive_summary": "2-3 short plain-English sentences",
    "key_findings": ["finding 1", "finding 2", "finding 3"],
    "verdict": "BENIGN|SUSPICIOUS|MALICIOUS",
    "verdict_rationale": "plain English explanation",
    "recommendations": ["clear action 1", "clear action 2", "clear action 3"]
  },
  "metadata": {
    "generator": "nvidia_nim",
    "model": "${config.model}",
    "timestamp": "${new Date().toISOString()}"
  }
}

Rules:
- Include one per_check entry for every item in payload.checks.
- summary_sentence must be one sentence and easy to understand.
- risk_level must be LOW, MODERATE, or HIGH.
- If uncertain, be conservative and explain that uncertainty briefly.`;

  const result = await postChatCompletion(prompt, 2400);
  if (!result.enabled) return result as ResultsAnalysis;

  const parsed = result.payload as Record<string, unknown>;
  const perCheck = Array.isArray(parsed.per_check) ? parsed.per_check : [];
  const normalizedPerCheck = payload.checks.map((check) => {
    const existing = perCheck.find((entry) => String((entry as Record<string, unknown>).name || '') === check.name) as Record<string, unknown> | undefined;
    return {
      name: check.name,
      status: check.status,
      summary_sentence: String(existing?.summary_sentence || check.evidence || `Check returned status ${check.status}.`).slice(0, 220),
      risk_level: String(existing?.risk_level || statusToRisk(check.status)).toUpperCase(),
    };
  });

  return {
    enabled: true,
    per_check: normalizedPerCheck,
    threat_report: normalizeThreatReport(parsed.threat_report),
    metadata: normalizeMetadata(parsed.metadata, config.model),
  };
}
