"""
NVIDIA NIM-powered analysis for URL audit checks.
"""
import json
import os
from datetime import datetime
from typing import Any, Dict, List

import requests


def _extract_json(text: str) -> Dict[str, Any]:
    raw = text.strip()
    if "```json" in raw:
        raw = raw.split("```json", 1)[1].split("```", 1)[0].strip()
    elif "```" in raw:
        raw = raw.split("```", 1)[1].split("```", 1)[0].strip()
    return json.loads(raw)


def _status_to_risk(status: str) -> str:
    mapping = {
        "PASS": "LOW",
        "INFO": "LOW",
        "WARN": "MODERATE",
        "FAIL": "HIGH",
        "SKIP": "LOW",
    }
    return mapping.get((status or "").upper(), "MODERATE")


def _normalize_per_check(per_check: Any) -> List[Dict[str, str]]:
    if not isinstance(per_check, list):
        return []

    normalized: List[Dict[str, str]] = []
    for entry in per_check:
        if not isinstance(entry, dict):
            continue
        status = str(entry.get("status") or "INFO").upper()
        normalized.append(
            {
                "name": str(entry.get("name") or "Unnamed check"),
                "status": status,
                "summary_sentence": str(entry.get("summary_sentence") or entry.get("summary") or "").strip(),
                "risk_level": str(entry.get("risk_level") or _status_to_risk(status)).upper(),
            }
        )
    return normalized


def _normalize_verdict(value: Any) -> str:
    text = str(value or "").strip().upper()
    if text in {"BENIGN", "SUSPICIOUS", "MALICIOUS"}:
        return text
    if text in {"LOW", "SAFE", "MINIMAL"}:
        return "BENIGN"
    if text in {"MEDIUM", "MODERATE"}:
        return "SUSPICIOUS"
    if text in {"HIGH", "CRITICAL", "SEVERE", "DANGEROUS"}:
        return "MALICIOUS"
    return "UNKNOWN"


def _normalize_report(report: Any) -> Dict[str, Any]:
    if not isinstance(report, dict):
        report = {}

    key_findings = report.get("key_findings")
    if isinstance(key_findings, str):
        key_findings = [line.strip(" -•\t") for line in key_findings.splitlines() if line.strip()]
    if not isinstance(key_findings, list):
        key_findings = []

    recommendations = report.get("recommendations")
    if isinstance(recommendations, str):
        recommendations = [line.strip(" -•\t") for line in recommendations.splitlines() if line.strip()]
    if not isinstance(recommendations, list):
        recommendations = []

    executive_summary = str(report.get("executive_summary") or report.get("summary") or "").strip()
    verdict = _normalize_verdict(report.get("verdict") or report.get("risk_level"))
    verdict_rationale = str(
            report.get("verdict_rationale") or report.get("rationale") or report.get("analysis") or ""
        ).strip()
    key_findings_out = [str(v).strip() for v in key_findings if str(v).strip()]
    recommendations_out = [str(v).strip() for v in recommendations if str(v).strip()]

    if not executive_summary:
        executive_summary = "The scan found mixed signals. Review failed and warning checks first."
    if not verdict_rationale:
        verdict_rationale = "Verdict is based on the number and severity of failed and warning checks."
    if not key_findings_out:
        key_findings_out = ["No detailed findings were generated by the model."]
    if not recommendations_out:
        recommendations_out = ["Review high-risk checks and remediate the flagged issues."]

    return {
        "executive_summary": executive_summary,
        "verdict": verdict,
        "verdict_rationale": verdict_rationale,
        "key_findings": key_findings_out,
        "recommendations": recommendations_out,
    }


def _normalize_metadata(metadata: Any, model: str) -> Dict[str, Any]:
    if not isinstance(metadata, dict):
        metadata = {}
    out = dict(metadata)
    out.setdefault("generator", "nvidia_nim")
    out.setdefault("model", model)
    out.setdefault("timestamp", f"{datetime.utcnow().isoformat()}Z")
    return out


def _truncate(value: str, limit: int = 420) -> str:
    if len(value) <= limit:
        return value
    return value[: limit - 3] + "..."


def _serialize_check_data(data: Any) -> str:
    if data is None:
        return ""
    try:
        return _truncate(json.dumps(data, default=str), 700)
    except Exception:
        return _truncate(str(data), 700)


def _build_prompt_payload(results: List[Any]) -> Dict[str, Any]:
    checks = []
    counts: Dict[str, int] = {"PASS": 0, "WARN": 0, "FAIL": 0, "INFO": 0, "SKIP": 0}
    for r in results:
        status = str(getattr(r, "status", "") or "").upper()
        counts[status] = counts.get(status, 0) + 1
        checks.append(
            {
                "id": getattr(r, "id", None),
                "name": getattr(r, "name", ""),
                "status": status,
                "evidence": _truncate((getattr(r, "evidence", "") or ""), 240),
                "data_excerpt": _serialize_check_data(getattr(r, "data", None)),
            }
        )
    return {"counts": counts, "checks": checks}


def _ensure_all_checks_present(per_check: List[Dict[str, str]], payload_checks: List[Dict[str, Any]]) -> List[Dict[str, str]]:
    seen = {entry.get("name"): entry for entry in per_check if entry.get("name")}
    ordered: List[Dict[str, str]] = []
    for source in payload_checks:
        name = str(source.get("name") or "Unnamed check")
        status = str(source.get("status") or "INFO").upper()
        current = seen.get(name)
        if current:
            ordered.append(current)
            continue
        evidence = str(source.get("evidence") or "").strip()
        summary = evidence if evidence else f"Check returned status {status}."
        ordered.append(
            {
                "name": name,
                "status": status,
                "summary_sentence": _truncate(summary, 220),
                "risk_level": _status_to_risk(status),
            }
        )
    return ordered


def analyze_text_with_nim(page_text: str, domain: str) -> Dict[str, Any]:
    api_key = os.getenv("NVIDIA_NIM_API_KEY")
    base_url = os.getenv("NVIDIA_NIM_BASE_URL", "https://integrate.api.nvidia.com/v1")
    model = os.getenv("NVIDIA_NIM_MODEL", "meta/llama-3.1-70b-instruct")
    timeout = int(os.getenv("NVIDIA_NIM_TIMEOUT", "60"))

    if not api_key:
        return {"enabled": False, "error": "NVIDIA_NIM_API_KEY not configured"}

    prompt = f"""Analyze this webpage for phishing/security risks. Domain: {domain}

Text: {page_text[:8000]}

Respond with JSON only:
{{
  "grammar_issues": "YES|NO: reason",
  "too_good_claims": "YES|NO: reason",
  "credential_or_payment_risk": "YES|NO: reason",
  "brand_mismatch": "YES|NO: reason",
  "generic_content": "YES|NO: reason",
  "phishy_tone": "YES|NO: reason",
  "overall_risk": "LOW|MEDIUM|HIGH",
  "summary": "one sentence"
}}"""

    try:
        r = requests.post(
            f"{base_url}/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.2,
                "max_tokens": 1200,
            },
            timeout=timeout,
        )
        if not r.ok:
            return {"enabled": False, "error": f"NIM API error: {r.status_code}"}

        content = r.json()["choices"][0]["message"]["content"]
        parsed = _extract_json(content)
        return {"enabled": True, **parsed, "_via": "nvidia_nim"}
    except Exception as exc:  # noqa: BLE001
        return {"enabled": False, "error": str(exc)}


def analyze_results_with_nim(results: List[Any]) -> Dict[str, Any]:
    api_key = os.getenv("NVIDIA_NIM_API_KEY")
    base_url = os.getenv("NVIDIA_NIM_BASE_URL", "https://integrate.api.nvidia.com/v1")
    model = os.getenv("NVIDIA_NIM_MODEL", "meta/llama-3.1-70b-instruct")
    timeout = int(os.getenv("NVIDIA_NIM_TIMEOUT", "90"))

    if not api_key:
        return {"enabled": False, "error": "NVIDIA_NIM_API_KEY not configured"}

    payload = _build_prompt_payload(results)

    prompt = f"""Analyze these URL security check results and create a threat report.
Use plain English so a non-technical user can understand it.
Keep wording short and clear. Avoid jargon whenever possible.

Checks payload: {json.dumps(payload)}

Respond with JSON only:
{{
  "per_check": [
    {{"name": "check name", "status": "PASS|WARN|FAIL|INFO|SKIP", "summary_sentence": "simple one-line explanation", "risk_level": "LOW|MODERATE|HIGH"}}
  ],
  "threat_report": {{
    "executive_summary": "2-3 short plain-English sentences",
    "key_findings": ["finding 1", "finding 2", "finding 3"],
    "verdict": "BENIGN|SUSPICIOUS|MALICIOUS",
    "verdict_rationale": "plain English explanation",
    "recommendations": ["clear action 1", "clear action 2", "clear action 3"]
  }},
  "metadata": {{
    "generator": "nvidia_nim",
    "model": "{model}",
    "timestamp": "{datetime.utcnow().isoformat()}Z"
  }}
}}

Rules:
- Include one per_check entry for every item in payload.checks.
- summary_sentence max 180 characters.
- key_findings and recommendations must be practical and easy to follow.
"""

    try:
        r = requests.post(
            f"{base_url}/chat/completions",
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            json={
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "temperature": 0.2,
                "max_tokens": 2200,
            },
            timeout=timeout,
        )
        if not r.ok:
            return {"enabled": False, "error": f"NIM API error: {r.status_code}"}

        content = r.json()["choices"][0]["message"]["content"]
        parsed = _extract_json(content)
        analysis = parsed if isinstance(parsed, dict) else {}

        per_check = _normalize_per_check(analysis.get("per_check"))
        per_check = _ensure_all_checks_present(per_check, payload.get("checks", []))

        normalized = {
            "enabled": True,
            "per_check": per_check,
            "threat_report": _normalize_report(analysis.get("threat_report")),
            "metadata": _normalize_metadata(analysis.get("metadata"), model),
        }
        return normalized
    except Exception as exc:  # noqa: BLE001
        return {"enabled": False, "error": str(exc)}
