type ConfigMap = {
  VIRUSTOTAL_API_KEY: string;
  ABUSEIPDB_API_KEY: string;
  GOOGLE_SAFE_BROWSING_API_KEY: string;
  GTMETRIX_API_KEY: string;
  GTMETRIX_USERNAME: string;
  GTMETRIX_LOCATION: string;
  GTMETRIX_LOCATION_SECONDARY: string;
  DISABLE_GTMETRIX: string;
  IPINFO_TOKEN: string;
  CRUNCHBASE_API_KEY: string;
  SERPAPI_API_KEY: string;
  DOMAINTOOLS_API_KEY: string;
  SPAMHAUS_API_KEY: string;
  SURBL_API_KEY: string;
  PAGESPEED_KEY_FILE: string;
  AI_PROVIDER: string;
  NVIDIA_NIM_API_KEY: string;
  NVIDIA_TEXT_MODEL: string;
  NVIDIA_NIM_MODEL: string;
  NVIDIA_NIM_BASE_URL: string;
  NVIDIA_TIMEOUT: string;
  NVIDIA_NIM_TIMEOUT: string;
  URL_AUDIT_DB_PATH: string;
  DATABASE_URL: string;
};

const HARDCODED_CONFIG: ConfigMap = {
  VIRUSTOTAL_API_KEY: 'fb4000cbc3de4811874ad4e12b864a52b388330d76bf2143e718aab1968eda24',
  ABUSEIPDB_API_KEY: '4cca40f43d63d15afdc605ce8cc346857159c7edfd349e020a924cbe32d3d994c9df882931326e69',
  GOOGLE_SAFE_BROWSING_API_KEY: 'AIzaSyDOkBbBqIJ_vTi7nUnXK8my1RqzZB13vaI',
  GTMETRIX_API_KEY: 'dcc25257cd449f8b43eae424b54950e6',
  GTMETRIX_USERNAME: '',
  GTMETRIX_LOCATION: 'london_uk',
  GTMETRIX_LOCATION_SECONDARY: 'vancouver_canada',
  DISABLE_GTMETRIX: '1',
  IPINFO_TOKEN: 'bbf95787966961',
  CRUNCHBASE_API_KEY: '',
  SERPAPI_API_KEY: '3a6b917e883c7384a493236042ff8a6b8fe5feae13f1a93feffacb28ed395a2c',
  DOMAINTOOLS_API_KEY: '',
  SPAMHAUS_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJpbnRlbCIsImV4cCI6MTc1NjQ1MzUwNSwiaWF0IjoxNzU2MzY3MTA1LCJpc3MiOiJzaGFwaS1hdXRoIiwibmJmIjoxNzU2MzY3MTA1LCJzdWIiOiIzNTAzMDAyNiIsInRpZXIiOnsiYWRzIjoiWEJMLEJDTCxDU1MsRE9NQUlOLEEuVUgiLCJhZHciOjAsImx2bCI6InN0ZCIsInFtaCI6MjAwMDAwMCwicW1zIjoyMDAwMDAwLCJybF9xcGgiOjI1MDAwMCwicmxfcXBtIjoxMjAwMDAsInJsX3FwcyI6MjAwfSwidXNyIjoidmlwcGFydGhpcGF1bEBrYXJ1bnlhLmVkdS5pbiJ9.lQ4UA-aIwCvOzj_5UuzJgH9taq-Qi_pqe80FXe4qeyw',
  SURBL_API_KEY: '',
  PAGESPEED_KEY_FILE: './pagespeed_key.json',
  AI_PROVIDER: 'nvidia',
  NVIDIA_NIM_API_KEY: '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',
  NVIDIA_TEXT_MODEL: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
  NVIDIA_NIM_MODEL: 'nvidia/llama-3.3-nemotron-super-49b-v1.5',
  NVIDIA_NIM_BASE_URL: 'https://integrate.api.nvidia.com/v1',
  NVIDIA_TIMEOUT: '60',
  NVIDIA_NIM_TIMEOUT: '60',
  URL_AUDIT_DB_PATH: './data/url_audit.db',
  DATABASE_URL: 'mysql+aiomysql://root:admin@localhost:3306/phishnet_social',
};

export function getServerConfig(): ConfigMap {
  return {
    VIRUSTOTAL_API_KEY: process.env.VIRUSTOTAL_API_KEY || HARDCODED_CONFIG.VIRUSTOTAL_API_KEY,
    ABUSEIPDB_API_KEY: process.env.ABUSEIPDB_API_KEY || HARDCODED_CONFIG.ABUSEIPDB_API_KEY,
    GOOGLE_SAFE_BROWSING_API_KEY: process.env.GOOGLE_SAFE_BROWSING_API_KEY || HARDCODED_CONFIG.GOOGLE_SAFE_BROWSING_API_KEY,
    GTMETRIX_API_KEY: process.env.GTMETRIX_API_KEY || HARDCODED_CONFIG.GTMETRIX_API_KEY,
    GTMETRIX_USERNAME: process.env.GTMETRIX_USERNAME || HARDCODED_CONFIG.GTMETRIX_USERNAME,
    GTMETRIX_LOCATION: process.env.GTMETRIX_LOCATION || HARDCODED_CONFIG.GTMETRIX_LOCATION,
    GTMETRIX_LOCATION_SECONDARY: process.env.GTMETRIX_LOCATION_SECONDARY || HARDCODED_CONFIG.GTMETRIX_LOCATION_SECONDARY,
    DISABLE_GTMETRIX: process.env.DISABLE_GTMETRIX || HARDCODED_CONFIG.DISABLE_GTMETRIX,
    IPINFO_TOKEN: process.env.IPINFO_TOKEN || HARDCODED_CONFIG.IPINFO_TOKEN,
    CRUNCHBASE_API_KEY: process.env.CRUNCHBASE_API_KEY || HARDCODED_CONFIG.CRUNCHBASE_API_KEY,
    SERPAPI_API_KEY: process.env.SERPAPI_API_KEY || HARDCODED_CONFIG.SERPAPI_API_KEY,
    DOMAINTOOLS_API_KEY: process.env.DOMAINTOOLS_API_KEY || HARDCODED_CONFIG.DOMAINTOOLS_API_KEY,
    SPAMHAUS_API_KEY: process.env.SPAMHAUS_API_KEY || HARDCODED_CONFIG.SPAMHAUS_API_KEY,
    SURBL_API_KEY: process.env.SURBL_API_KEY || HARDCODED_CONFIG.SURBL_API_KEY,
    PAGESPEED_KEY_FILE: process.env.PAGESPEED_KEY_FILE || HARDCODED_CONFIG.PAGESPEED_KEY_FILE,
    AI_PROVIDER: process.env.AI_PROVIDER || HARDCODED_CONFIG.AI_PROVIDER,
    NVIDIA_NIM_API_KEY: process.env.NVIDIA_NIM_API_KEY || HARDCODED_CONFIG.NVIDIA_NIM_API_KEY,
    NVIDIA_TEXT_MODEL: process.env.NVIDIA_TEXT_MODEL || HARDCODED_CONFIG.NVIDIA_TEXT_MODEL,
    NVIDIA_NIM_MODEL: process.env.NVIDIA_NIM_MODEL || HARDCODED_CONFIG.NVIDIA_NIM_MODEL,
    NVIDIA_NIM_BASE_URL: process.env.NVIDIA_NIM_BASE_URL || HARDCODED_CONFIG.NVIDIA_NIM_BASE_URL,
    NVIDIA_TIMEOUT: process.env.NVIDIA_TIMEOUT || HARDCODED_CONFIG.NVIDIA_TIMEOUT,
    NVIDIA_NIM_TIMEOUT: process.env.NVIDIA_NIM_TIMEOUT || HARDCODED_CONFIG.NVIDIA_NIM_TIMEOUT,
    URL_AUDIT_DB_PATH: process.env.URL_AUDIT_DB_PATH || HARDCODED_CONFIG.URL_AUDIT_DB_PATH,
    DATABASE_URL: process.env.DATABASE_URL || HARDCODED_CONFIG.DATABASE_URL,
  };
}

export function getProviderStatuses(): Record<string, boolean> {
  const config = getServerConfig();
  return {
    virustotal: Boolean(config.VIRUSTOTAL_API_KEY),
    abuseipdb: Boolean(config.ABUSEIPDB_API_KEY),
    googleSafeBrowsing: Boolean(config.GOOGLE_SAFE_BROWSING_API_KEY),
    gtmetrix: Boolean(config.GTMETRIX_API_KEY) && config.DISABLE_GTMETRIX !== '1',
    ipinfo: Boolean(config.IPINFO_TOKEN),
    crunchbase: Boolean(config.CRUNCHBASE_API_KEY),
    serpapi: Boolean(config.SERPAPI_API_KEY),
    domaintools: Boolean(config.DOMAINTOOLS_API_KEY),
    spamhaus: Boolean(config.SPAMHAUS_API_KEY),
    surbl: Boolean(config.SURBL_API_KEY),
    pagespeedKeyFile: Boolean(config.PAGESPEED_KEY_FILE),
    aiProvider: Boolean(config.AI_PROVIDER),
    nvidiaNim: Boolean(config.NVIDIA_NIM_API_KEY),
    databaseUrl: Boolean(config.DATABASE_URL),
  };
}
